language: objective-c
cache: cocoapods

before_install:
  - sudo easy_install cpp-coveralls
  - gem install cocoapods

script:
  - make test REPORTER=pretty

after_success:
  - make send-to-coveralls

